<?php

namespace AppBundle\Repository;

/**
 * LadderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LadderRepository extends \Doctrine\ORM\EntityRepository
{
}
